spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: journaldb
      auto-index-creation: true

  redis:
    host: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    port: 15362
    password: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  mail:
    host: XXXXXXXXX
    port: 587
    username: XXXXXXXXXXXXXXXX@gmail.com
    password: XXXXXX
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            client-secret: XXXXXXXXXXXXXXXXXXXXX


weather:
    api:
      key : 4e580325e91f01497eb71d8e64919df3

