spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: journaldb
      auto-index-creation: true
#      uri: mongodb+srv://lakshyahidau2005:lakshyahidau2005@cluster0.5idrq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

  redis:
    host: redis-15362.c301.ap-south-1-1.ec2.redns.redis-cloud.com:15362
    port: 15362
    password: 7S2J3lgtNZEuQS72mib8MqSXFD25HzFa

  mail:
    host: smtp.gmail.com
    port: 587
    username: iitjeepreparation03@gmail.com
    password: java mail
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 778814146199-ampjd3f0r9rhqdluo8iknbnfa5veqsip.apps.googleusercontent.com
            client-secret: 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


weather:
    api:
      key : 4e580325e91f01497eb71d8e64919df3

